# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66eb28d596af56c84f280790fcfe858c13997a7c380def5a50778babea6e77bc8a54fbaae42b3831cbcb5604a181de0b612ae97b3ae5d0ca06f655822634820b

test:
  secret_key_base: 161daffd2cd2f3276333220661d78b39033e9d8116db5d444ce9de349a1ca98f66c94518022426d29bfa1a54194cfa294e8c2de54f8d5017a5b3b566f57a4485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
